{TEXT("面粉"), TEXT("Flour")},
{TEXT("水"), TEXT("Water")},
{TEXT("面团"), TEXT("Dough")},
{TEXT("酵母"), TEXT("Yeast")},
{TEXT("酒精"), TEXT("Alcohol")},
{TEXT("生命  %.0f / %.0f"), TEXT("Health  %.0f / %.0f")},
{TEXT("变身  %.0f%%"), TEXT("Transformation  %.0f%%")},
{TEXT("● 酵母形态 · 耗尽后还原"), TEXT("Yeast form - Reverts at 0%")},
{TEXT("● 面团形态 · [E] 变身"), TEXT("Dough form - [E] Transform")},
{TEXT("酒精  × %d"), TEXT("Alcohol  × %d")},
{TEXT("每槽上限 %d · 共 %d 槽"), TEXT("Stack limit %d · %d slots")},
{TEXT("选择物品查看用途，再点击使用。"), TEXT("Select an item to inspect it, then click Use.")},
{TEXT(" · 恢复 %.0f 生命"), TEXT(" · Restores %.0f health")},
{TEXT(" · +%.0f%% 变身值"), TEXT(" · +%.0f%% transformation")},
{TEXT(" · 制作 / 战斗材料"), TEXT(" · Crafting / combat material")},
{TEXT("酵母形态 · 可以制作"), TEXT("Yeast form · Crafting available")},
{TEXT("变身值满后按 E 进入酵母形态"), TEXT("At full transformation, press E to enter Yeast form")},
{TEXT("当前无法使用该物品。"), TEXT("This item cannot be used right now.")},
{TEXT("制作完成，物品已加入背包。"), TEXT("Crafting complete. The item is in your inventory.")},
{TEXT("制作失败：请检查材料、形态和空间。"), TEXT("Crafting failed. Check materials, form and inventory space.")},
{TEXT("加载失败。"), TEXT("Loading failed.")},
{TEXT("存档 %d"), TEXT("Save %d")},
{TEXT("新建失败。"), TEXT("Unable to create a new save.")},
{TEXT("存档已删除。"), TEXT("Save deleted.")},
{TEXT("删除失败。"), TEXT("Deletion failed.")},
{TEXT("保存成功。"), TEXT("Game saved.")},
{TEXT("保存失败。"), TEXT("Saving failed.")},
{TEXT("保存失败，未返回标题。"), TEXT("Saving failed. You have not returned to the title screen.")},
{TEXT("主音量  %.0f%%"), TEXT("Master volume  %.0f%%")},
{TEXT("窗口"), TEXT("Windowed")},
{TEXT("无边框"), TEXT("Borderless")},
{TEXT("全屏"), TEXT("Fullscreen")},
{TEXT("低"), TEXT("Low")},
{TEXT("中"), TEXT("Medium")},
{TEXT("高"), TEXT("High")},
{TEXT("极高"), TEXT("Ultra")},
{TEXT("设置已保存；全屏与分辨率请在独立运行窗口检查。"), TEXT("Settings saved. Check fullscreen and resolution in a standalone window.")},
{TEXT("长按采集"), TEXT("Hold to gather")},
{TEXT("变身值耗尽，恢复面团形态"), TEXT("Transformation depleted. Returned to Dough form.")},
{TEXT("按住 F 采集%s  ·  %d%%"), TEXT("Hold F to gather %s  ·  %d%%")},
{TEXT("变身值达到 100% 后按 E 变身"), TEXT("Reach 100% transformation, then press E to transform")},
{TEXT("酵母形态：已开放合成"), TEXT("Yeast form: crafting unlocked")},
{TEXT("酒精不足：疾跑累计或酵母形态合成可获得"), TEXT("Not enough alcohol. Earn it by sprinting or craft it in Yeast form.")},
{TEXT("此物品用于合成或投掷"), TEXT("This item is used for crafting or throwing")},
{TEXT("当前无需使用此物品"), TEXT("You do not need to use this item right now")},
{TEXT("制作完成"), TEXT("Crafting complete")},
{TEXT("制作失败：检查酵母形态、材料和背包空间"), TEXT("Crafting failed: check Yeast form, materials and inventory space")},
{TEXT("存档已保存"), TEXT("Game saved")},
{TEXT("物品名称"), TEXT("Item name")},
{TEXT("配方名称"), TEXT("Recipe name")},
{TEXT("需要：材料 × 数量（拥有 0）"), TEXT("Requires: material × quantity (owned: 0)")},
{TEXT("获得：物品 × 数量"), TEXT("Produces: item × quantity")},
{TEXT("仅酵母形态可制作"), TEXT("Requires Yeast form")},
{TEXT("制作一份"), TEXT("Craft one")},
{TEXT("存档槽位"), TEXT("Save slot")},
{TEXT("保存时间 / 新冒险"), TEXT("Save time / New adventure")},
{TEXT("加载"), TEXT("Load")},
{TEXT("新建"), TEXT("New")},
{TEXT("删除"), TEXT("Delete")},
{TEXT("取消"), TEXT("Cancel")},
{TEXT("生命 100 / 100"), TEXT("Health 100 / 100")},
{TEXT("变身 0%"), TEXT("Transformation 0%")},
{TEXT("疾跑酿造"), TEXT("Sprint brewing")},
{TEXT("停止后保留进度"), TEXT("Progress kept when stopped")},
{TEXT("酒精 × 0"), TEXT("Alcohol × 0")},
{TEXT("WASD 移动   Shift 疾跑   空格 冲刺   右键拖拽 视角   左键 投掷   F 采集   B 背包   Tab 制作   Esc 菜单"), TEXT("WASD Move   Shift Sprint   Space Dash   Hold RMB Camera   LMB Throw   F Gather   B Inventory   Tab Craft   Esc Menu")},
{TEXT("按住 F 采集 · 0%"), TEXT("Hold F to gather · 0%")},
{TEXT("面团世界"), TEXT("Dough World")},
{TEXT("探索 · 收集 · 发酵 · 生存"), TEXT("Explore · Gather · Ferment · Survive")},
{TEXT("开始游戏"), TEXT("Start game")},
{TEXT("设置"), TEXT("Settings")},
{TEXT("退出游戏"), TEXT("Quit game")},
{TEXT("选择存档"), TEXT("Choose a save")},
{TEXT("最多 3 个存档。新建不会覆盖已有存档；删除需要再次确认。"), TEXT("Up to 3 saves. Creating a new save never overwrites an existing one. Deletion requires confirmation.")},
{TEXT("返回标题"), TEXT("Return to title")},
{TEXT("背包"), TEXT("Inventory")},
{TEXT("点击物品查看用途与使用。按 B 返回游戏。"), TEXT("Select an item to inspect or use it. Press B to return to the game.")},
{TEXT("每槽上限 40 · 共 24 槽"), TEXT("Stack limit 40 · 24 slots")},
{TEXT("选择物品查看用途"), TEXT("Select an item to inspect it")},
{TEXT("使用一个"), TEXT("Use one")},
{TEXT("返回游戏"), TEXT("Return to game")},
{TEXT("制作台"), TEXT("Crafting")},
{TEXT("左侧背包，右侧配方。按 Tab 返回游戏。"), TEXT("Inventory on the left, recipes on the right. Press Tab to return to the game.")},
{TEXT("游戏已暂停"), TEXT("Game paused")},
{TEXT("保存进度后可以继续探索或返回标题。"), TEXT("Save your progress, then continue exploring or return to the title screen.")},
{TEXT("继续游戏"), TEXT("Continue game")},
{TEXT("保存游戏"), TEXT("Save game")},
{TEXT("保存并返回标题"), TEXT("Save and return to title")},
{TEXT("返回标题（不保存）"), TEXT("Return to title without saving")},
{TEXT("音量即时生效，图像设置需点击应用。"), TEXT("Volume updates immediately. Apply to save graphics.")},
{TEXT("主音量 100%"), TEXT("Master volume 100%")},
{TEXT("分辨率"), TEXT("Resolution")},
{TEXT("显示模式"), TEXT("Display mode")},
{TEXT("画质"), TEXT("Graphics quality")},
{TEXT("垂直同步"), TEXT("Vertical sync")},
{TEXT("应用并保存"), TEXT("Apply and save")},
{TEXT("返回"), TEXT("Back")},
{TEXT("面团暂时失去了活力"), TEXT("Your dough has lost its vitality")},
{TEXT("加载上次保存的进度，或返回标题。"), TEXT("Load your last saved progress or return to the title screen.")},
{TEXT("加载当前存档"), TEXT("Load current save")},
{TEXT("操作反馈提示"), TEXT("Action feedback")},
{TEXT("（拥有 %d）"), TEXT(" (owned: %d)")},
{TEXT("空槽"), TEXT("Empty slot")},
{TEXT("需要："), TEXT("Requires: ")},
{TEXT("获得："), TEXT("Produces: ")},
{TEXT("任意形态可制作"), TEXT("Craftable in either form")},
{TEXT("材料 / 形态 / 背包空间不足"), TEXT("Check materials / form / inventory space")},
{TEXT("存档 %d · 空槽位"), TEXT("Save %d · Empty slot")},
{TEXT("开始一段新的冒险"), TEXT("Start a new adventure")},
{TEXT("确认永久删除"), TEXT("Confirm permanent deletion")},
{TEXT("可交互物体"), TEXT("Interactable object")},
{TEXT("交互"), TEXT("Interact")},
{TEXT("无法读取的存档（可删除）"), TEXT("Unreadable save (can be deleted)")},
{TEXT("存档格式无法读取或版本不兼容。"), TEXT("The save format is unreadable or its version is incompatible.")},
{TEXT("存档地图不存在或不是当前玩法地图。"), TEXT("The saved map is missing or is not the current gameplay map.")},
{TEXT("存档包含无效的玩家属性或位置，已停止加载。"), TEXT("Loading stopped: the save contains invalid player attributes or a position.")},
{TEXT("存档背包与当前物品或容量配置不兼容；原存档已保留。"), TEXT("The saved inventory is incompatible with the current items or capacity. The original save has been preserved.")},
{TEXT("存档包含无效或重复的场景物件记录。"), TEXT("The save contains invalid or duplicate world object records.")},
{TEXT("只能使用存档槽 1 至 3。"), TEXT("Only save slots 1 through 3 are available.")},
{TEXT("游戏世界尚未准备好。"), TEXT("The game world is not ready yet.")},
{TEXT("该槽位已有存档，请先删除或选择空槽位。"), TEXT("This slot already contains a save. Delete it first or choose an empty slot.")},
{TEXT("无法创建存档对象。"), TEXT("Unable to create the save object.")},
{TEXT("冒险 {0}"), TEXT("Adventure {0}")},
{TEXT("写入新存档失败，请检查磁盘空间与写入权限。"), TEXT("Unable to write the new save. Check disk space and write permissions.")},
{TEXT("该存档槽为空。"), TEXT("This save slot is empty.")},
{TEXT("删除存档失败，文件可能被占用。"), TEXT("Unable to delete the save. The file may be in use.")},
{TEXT("尚未进入存档，无法保存标题界面。"), TEXT("No save slot is active. You cannot save from the title screen.")},
{TEXT("当前玩家尚未准备好，未覆盖原存档。"), TEXT("The player is not ready yet. The original save has not been overwritten.")},
{TEXT("角色已死亡，保留上次存档供重新加载。"), TEXT("The character has died. The previous save has been kept for reloading.")},
{TEXT("当前关卡不是正式玩法测试地图，未覆盖原存档。"), TEXT("This level is not the designated gameplay test map. The original save has not been overwritten.")},
{TEXT("保存失败，请检查磁盘空间与写入权限。"), TEXT("Saving failed. Check disk space and write permissions.")},
{TEXT("标题地图不存在，已留在当前关卡。"), TEXT("The title map is missing. You have remained in the current level.")},
{TEXT("语言"), TEXT("Language")},
{TEXT("语言 / Language"), TEXT("Language")},
{TEXT("简体中文"), TEXT("Simplified Chinese")},
